### ISSUE TITLE
Inspekcja drogowa

### ISSUE THREAD

**Issue by zlew-chan** [Creper132/CM-Pack-Remover#1]
Czemu państwo nie użyliście np. c# tylko robicie obrzydliwe spaghetti w batchu?

**Comment by Creper132** [comment]
ponieważ pracujemy z panem raizu o zrobienie w c#

**Comment by zlew-chan** [comment]
> ponieważ pracujemy z panem raizu o zrobienie w c#

tylko, że czemu od razu tego nie zrobiliście w c#, czy klasa system.io jest aż tak trudna?

**Comment by zlew-chan** [comment]
Gdzie ta wersja c#?
